CREATE TABLE Hindi_Songs (SongID Integer PRIMARY KEY,SongName varchar(100),ArtistID Integer NOT NULL,ArtistName varchar(100),              Lyrics varchar(10000),ReleaseDate Date,Rating Integer,TotalReviews Integer,GenreID Integer,MoodID Integer, FilmID Integer,SongFilePath varchar(200),Image Blob(16),FOREIGN KEY (GenreID) REFERENCES Genre(GenreID),FOREIGN KEY (ArtistID) REFERENCES Artist(ArtistID), FOREIGN KEY (MoodID) REFERENCES Mood(MoodID) ,FOREIGN KEY (FilmID) REFERENCES FilmMakers(FilmID));

INSERT INTO Hindi_Songs(SongID, SongName, ArtistID, ArtistName, Lyrics, ReleaseDate, Rating, TotalReviews, GenreID, MoodID, FilmID, SongFilePath, Image)
VALUES(
			401,
			'Ratta Maar',
			6,
			'Vishal Shekar',     
			"/home/akshyta/Desktop/DBMS_Project/Lyrics/H1.txt",    
			'2018-5-15',
			3, 		
			100,  	
			901,		
			105,		
			1,         
			"/home/akshyta/Desktop/DBMS_Project/Songs/H1.mp3",
			"/home/akshyta/Desktop/DBMS_Project/Images/H1.jpg"
),

(
			402,
			'Radha',
			5,
			'Shreya Ghoshal',
			"/home/akshyta/Desktop/DBMS_Project/Lyrics/H2.txt",    
			'2016-10-10', 	
			5,
			129,
			901, 
			101, 
			1, 
			"/home/akshyta/Desktop/DBMS_Project/Songs/H2.mp3",
			"/home/akshyta/Desktop/DBMS_Project/Images/H2.jpg"
),

(
			403,
			'Aal Izz Well',
			19,
			'Shaan',
			"/home/akshyta/Desktop/DBMS_Project/Lyrics/H3.txt",    
			'2016-5-2',
			5,
			100,
			901, 
			101, 
			2, 
			"/home/akshyta/Desktop/DBMS_Project/Songs/H3.mp3",
			"/home/akshyta/Desktop/DBMS_Project/Images/H3.jpg"
),

(
			404,
			'Zoobi Doobi',
			5,
			'Shreya Ghoshal',
			"/home/akshyta/Desktop/DBMS_Project/Lyrics/H4.txt",    
			'2017-2-13',
			3,
			70,
			901, 
			101, 
			2,
			"/home/akshyta/Desktop/DBMS_Project/Songs/H4.mp3",
			"/home/akshyta/Desktop/DBMS_Project/Images/H4.jpg"
),

(
			405,
			'Garmi',
			4,
			'Neha Kakkar',
			"/home/akshyta/Desktop/DBMS_Project/Lyrics/H5.txt",    
			'2019-2-18',
			5,
			200,
			904, 
			102, 
			3,
			"/home/akshyta/Desktop/DBMS_Project/Songs/H5.mp3",
			"/home/akshyta/Desktop/DBMS_Project/Images/H5.jpg"
),

(
			406,
			'Kho Jaane De',
			20,
			'S.D Burman',
			"/home/akshyta/Desktop/DBMS_Project/Lyrics/H6.txt",    
			'2016-5-2',
			4,
			159,
			901, 
			105,
			4,
			"/home/akshyta/Desktop/DBMS_Project/Songs/H6.mp3",
			"/home/akshyta/Desktop/DBMS_Project/Images/H6.jpg"
),


(
			407,
			'Bhagwaan Hai Kahan Re Tu',
			10,
			'Sonu Nigam',     
			"/home/akshyta/Desktop/DBMS_Project/Lyrics/H7.txt",    
			'2012-7-15',
			5, 	
			200,  	
			901,		
			104,		
			5,         
			"/home/akshyta/Desktop/DBMS_Project/Songs/H7.mp3",
			"/home/akshyta/Desktop/DBMS_Project/Images/H7.jpg"
),

(
			408,
			'Chann Chann',
			5,
			'Shreya Ghoshal',
			"/home/akshyta/Desktop/DBMS_Project/Lyrics/H8.txt",    
			'2015-11-30',
			4,
			50,
			901, 
			101,
			6, 
			"/home/akshyta/Desktop/DBMS_Project/Songs/H8.mp3",
			"/home/akshyta/Desktop/DBMS_Project/Images/H8.jpg"
),

(
			409,
			'Subah Ho Gayi Maamu',
			19,
			'Shaan',
			"/home/akshyta/Desktop/DBMS_Project/Lyrics/H9.txt",    
			'2014-6-8',
			4,
			100,
			901,
			101, 
			6, 
			"/home/akshyta/Desktop/DBMS_Project/Songs/H9.mp3",
			"/home/akshyta/Desktop/DBMS_Project/Images/H9.jpg"
),

(
			410,
			'Main Badiya Tu Bhi Badiya',
			10,
			'Sonu Nigam',
			"/home/akshyta/Desktop/DBMS_Project/Lyrics/H10.txt",    
			'2010-10-21',
			3,
			130,
			905, 
			102, 
			7,
			"/home/akshyta/Desktop/DBMS_Project/Songs/H10.mp3",
			"/home/akshyta/Desktop/DBMS_Project/Images/H10.jpg"
),
(
			411,
			'Yaad Piya ki aane lagi',
			4,
			'Neha Kakkar',
			"/home/akshyta/Desktop/DBMS_Project/Lyrics/H11.txt",    
			'2010-10-21',
			3,
			200,
			905,
			104, 
			8,
			"/home/akshyta/Desktop/DBMS_Project/Songs/H11.mp3",
			"/home/akshyta/Desktop/DBMS_Project/Images/H11.jpg"
),
(
			412,
			'Sauda Khara Khara',
			15,
			'Diljit Dosanjh',
			"/home/akshyta/Desktop/DBMS_Project/Lyrics/H12.txt",    
			'2010-10-21',
			5,
			179,
			901, 
			102,
			11,
			"/home/akshyta/Desktop/DBMS_Project/Songs/H12.mp3",
			"/home/akshyta/Desktop/DBMS_Project/Images/H12.jpg"
),
(
			413,
			'Chandigarh Mein',
			13,
			'Badshah',
			"/home/akshyta/Desktop/DBMS_Project/Lyrics/H13.txt",    
			'2010-10-21',
			4,
			131,
			903,
			102, 
			11,
			"/home/akshyta/Desktop/DBMS_Project/Songs/H13.mp3",
			"/home/akshyta/Desktop/DBMS_Project/Images/H13.jpg"
),
(
			414,
			'Badla',
			2,
			'Arijit Singh',
			"/home/akshyta/Desktop/DBMS_Project/Lyrics/H14.txt",    
			'2010-10-21',
			3,
			130,
			905, 
			102, 
			12,
			"/home/akshyta/Desktop/DBMS_Project/Songs/H14.mp3",
			"/home/akshyta/Desktop/DBMS_Project/Images/H14.jpg"
),
(
			415,
			'Awari',
			1,
			'Alka Yagnik',
			"/home/akshyta/Desktop/DBMS_Project/Lyrics/H15.txt",    
			'2010-10-21',
			4,
			132,
			904, 
			101, 
			39,
			"/home/akshyta/Desktop/DBMS_Project/Songs/H15.mp3",
			"/home/akshyta/Desktop/DBMS_Project/Images/H15.jpg"
),
(
			416,
			'Sher Aaya Sher',
			20,
			'S.D Burman',
			"/home/akshyta/Desktop/DBMS_Project/Lyrics/H16.txt",    
			'2010-10-21',
			3,
			129,
			905,
			102, 
			13,
			"/home/akshyta/Desktop/DBMS_Project/Songs/H16.mp3",
			"/home/akshyta/Desktop/DBMS_Project/Images/H16.jpg"
),
(
			417,
			'Chaandaniya',
			3,
			'Asha Bhosle',
			"/home/akshyta/Desktop/DBMS_Project/Lyrics/H17.txt",    
			'2010-10-21',
			2,
			190,
			909, 
			103, 
			37,
			"/home/akshyta/Desktop/DBMS_Project/Songs/H17.mp3",
			"/home/akshyta/Desktop/DBMS_Project/Images/H17.jpg"
),
(
			418,
			'Mujhe Chaand Pe Le Chalo',
			23,
			'Richa Sharma',
			"/home/akshyta/Desktop/DBMS_Project/Lyrics/H18.txt",    
			'2010-10-21',
			4,
			134,
			905, 
			102, 
			7,
			"/home/akshyta/Desktop/DBMS_Project/Songs/H18.mp3",
			"/home/akshyta/Desktop/DBMS_Project/Images/H18.jpg"
),
(
			419,
			'Mere Sapnon Ki Rani',
			7,
			'Kishore Kumar',
			"/home/akshyta/Desktop/DBMS_Project/Lyrics/H19.txt",    
			'2010-10-21',
			3,
			120,
			901, 
			101, 
			41,
			"/home/akshyta/Desktop/DBMS_Project/Songs/H19.mp3",
			"/home/akshyta/Desktop/DBMS_Project/Images/H19.jpg"
),
(
			420,
			'Hoor',
			9,
			'Atif Aslam',
			"/home/akshyta/Desktop/DBMS_Project/Lyrics/H20.txt",    
			'2010-10-21',
			3,
			132,
			901, 
			101, 
			19,
			"/home/akshyta/Desktop/DBMS_Project/Songs/H20.mp3",
			"/home/akshyta/Desktop/DBMS_Project/Images/H20.jpg"
),
(
			421,
			'Radio',
			8,
			'A.R. Rahman',
			"/home/akshyta/Desktop/DBMS_Project/Lyrics/H21.txt",    
			'2010-10-21',
			3,
			140,
			901, 
			103, 
			21,
			"/home/akshyta/Desktop/DBMS_Project/Songs/H21.mp3",
			"/home/akshyta/Desktop/DBMS_Project/Images/H21.jpg"
),
(
			422,
			'India Waale',
			16,
			'Sankar Mahadevan',
			"/home/akshyta/Desktop/DBMS_Project/Lyrics/H22.txt",    
			'2010-10-21',
			2,
			130,
			901, 
			101, 
			38,
			"/home/akshyta/Desktop/DBMS_Project/Songs/H22.mp3",
			"/home/akshyta/Desktop/DBMS_Project/Images/H22.jpg"
),
(
			423,
			'Badhaaiyan Tenu',
			22,
			'Benny Dayal',
			"/home/akshyta/Desktop/DBMS_Project/Lyrics/H23.txt",    
			'2010-10-21',
			5,
			140,
			901, 
			102, 
			17,
			"/home/akshyta/Desktop/DBMS_Project/Songs/H23.mp3",
			"/home/akshyta/Desktop/DBMS_Project/Images/H23.jpg"
),
(
			424,
			'Tera Ghata',
			21,
			'Gajendra Verma',
			"/home/akshyta/Desktop/DBMS_Project/Lyrics/H24.txt",    
			'2010-10-21',
			3,
			145,
			901, 
			104, 
			41,
			"/home/akshyta/Desktop/DBMS_Project/Songs/H24.mp3",
			"/home/akshyta/Desktop/DBMS_Project/Images/H24.jpg"
),
(
			425,
			'East Aur West',
			14,
			'Anu Malik',
			"/home/akshyta/Desktop/DBMS_Project/Lyrics/H25.txt",    
			'2010-10-21',
			1,
			130,
			905, 
			102, 
			20,
			"/home/akshyta/Desktop/DBMS_Project/Songs/H25.mp3",
			"/home/akshyta/Desktop/DBMS_Project/Images/H25.jpg"
);


